INCLUDE_PATH = -I "./containers" -I "./objects" -I "./utils" -I "D:\freeglut\include"

main: main.cpp 
	g++ main.cpp  $(INCLUDE_PATH) -std=c++11 -o main.exe -L "D:\freeglut\lib"  -lfreeglut -lopengl32 -lglu32